// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_INFO                 Severity = 1
	Severity_WARNING              Severity = 2
	Severity_ERROR                Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"INFO":                 1,
		"WARNING":              2,
		"ERROR":                3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type EngineType int32

const (
	EngineType_ENGINE_UNSPECIFIED EngineType = 0
	EngineType_GREP               EngineType = 1
	EngineType_AST                EngineType = 2
	EngineType_IMPORT_GRAPH       EngineType = 3
	EngineType_METRIC             EngineType = 4
	EngineType_STRUCTURE          EngineType = 5
	EngineType_ANTI_PATTERN       EngineType = 6
)

// Enum value maps for EngineType.
var (
	EngineType_name = map[int32]string{
		0: "ENGINE_UNSPECIFIED",
		1: "GREP",
		2: "AST",
		3: "IMPORT_GRAPH",
		4: "METRIC",
		5: "STRUCTURE",
		6: "ANTI_PATTERN",
	}
	EngineType_value = map[string]int32{
		"ENGINE_UNSPECIFIED": 0,
		"GREP":               1,
		"AST":                2,
		"IMPORT_GRAPH":       3,
		"METRIC":             4,
		"STRUCTURE":          5,
		"ANTI_PATTERN":       6,
	}
)

func (x EngineType) Enum() *EngineType {
	p := new(EngineType)
	*p = x
	return p
}

func (x EngineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineType) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[1].Descriptor()
}

func (EngineType) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[1]
}

func (x EngineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineType.Descriptor instead.
func (EngineType) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

type RuleStatus_Status int32

const (
	RuleStatus_STATUS_UNSPECIFIED RuleStatus_Status = 0
	RuleStatus_VALID              RuleStatus_Status = 1
	RuleStatus_INVALID            RuleStatus_Status = 2
	RuleStatus_STALE              RuleStatus_Status = 3
)

// Enum value maps for RuleStatus_Status.
var (
	RuleStatus_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "VALID",
		2: "INVALID",
		3: "STALE",
	}
	RuleStatus_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"VALID":              1,
		"INVALID":            2,
		"STALE":              3,
	}
)

func (x RuleStatus_Status) Enum() *RuleStatus_Status {
	p := new(RuleStatus_Status)
	*p = x
	return p
}

func (x RuleStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[2].Descriptor()
}

func (RuleStatus_Status) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[2]
}

func (x RuleStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleStatus_Status.Descriptor instead.
func (RuleStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{12, 0}
}

type EngineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*EngineRequest_Check
	//	*EngineRequest_Ping
	Command isEngineRequest_Command `protobuf_oneof:"command"`
}

func (x *EngineRequest) Reset() {
	*x = EngineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineRequest) ProtoMessage() {}

func (x *EngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineRequest.ProtoReflect.Descriptor instead.
func (*EngineRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (m *EngineRequest) GetCommand() isEngineRequest_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *EngineRequest) GetCheck() *CheckRequest {
	if x, ok := x.GetCommand().(*EngineRequest_Check); ok {
		return x.Check
	}
	return nil
}

func (x *EngineRequest) GetPing() *PingRequest {
	if x, ok := x.GetCommand().(*EngineRequest_Ping); ok {
		return x.Ping
	}
	return nil
}

type isEngineRequest_Command interface {
	isEngineRequest_Command()
}

type EngineRequest_Check struct {
	Check *CheckRequest `protobuf:"bytes,1,opt,name=check,proto3,oneof"`
}

type EngineRequest_Ping struct {
	Ping *PingRequest `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

func (*EngineRequest_Check) isEngineRequest_Command() {}

func (*EngineRequest_Ping) isEngineRequest_Command() {}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

type CheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectPath string   `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Rules       []*Rule  `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	TargetFiles []string `protobuf:"bytes,3,rep,name=target_files,json=targetFiles,proto3" json:"target_files,omitempty"` // empty = all files; non-empty = only these (--staged)
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *CheckRequest) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *CheckRequest) GetTargetFiles() []string {
	if x != nil {
		return x.TargetFiles
	}
	return nil
}

type Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity Severity   `protobuf:"varint,2,opt,name=severity,proto3,enum=engine.Severity" json:"severity,omitempty"`
	Message  string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Engine   EngineType `protobuf:"varint,4,opt,name=engine,proto3,enum=engine.EngineType" json:"engine,omitempty"`
	Scope    *RuleScope `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	// Types that are assignable to Spec:
	//
	//	*Rule_Grep
	//	*Rule_ImportGraph
	//	*Rule_AntiPattern
	//	*Rule_FunctionMetric
	Spec isRule_Spec `protobuf_oneof:"spec"`
}

func (x *Rule) Reset() {
	*x = Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Rule) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Rule) GetEngine() EngineType {
	if x != nil {
		return x.Engine
	}
	return EngineType_ENGINE_UNSPECIFIED
}

func (x *Rule) GetScope() *RuleScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (m *Rule) GetSpec() isRule_Spec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (x *Rule) GetGrep() *GrepSpec {
	if x, ok := x.GetSpec().(*Rule_Grep); ok {
		return x.Grep
	}
	return nil
}

func (x *Rule) GetImportGraph() *ImportGraphSpec {
	if x, ok := x.GetSpec().(*Rule_ImportGraph); ok {
		return x.ImportGraph
	}
	return nil
}

func (x *Rule) GetAntiPattern() *AntiPatternSpec {
	if x, ok := x.GetSpec().(*Rule_AntiPattern); ok {
		return x.AntiPattern
	}
	return nil
}

func (x *Rule) GetFunctionMetric() *FunctionMetricSpec {
	if x, ok := x.GetSpec().(*Rule_FunctionMetric); ok {
		return x.FunctionMetric
	}
	return nil
}

type isRule_Spec interface {
	isRule_Spec()
}

type Rule_Grep struct {
	Grep *GrepSpec `protobuf:"bytes,10,opt,name=grep,proto3,oneof"`
}

type Rule_ImportGraph struct {
	ImportGraph *ImportGraphSpec `protobuf:"bytes,11,opt,name=import_graph,json=importGraph,proto3,oneof"`
}

type Rule_AntiPattern struct {
	AntiPattern *AntiPatternSpec `protobuf:"bytes,12,opt,name=anti_pattern,json=antiPattern,proto3,oneof"`
}

type Rule_FunctionMetric struct {
	FunctionMetric *FunctionMetricSpec `protobuf:"bytes,13,opt,name=function_metric,json=functionMetric,proto3,oneof"`
}

func (*Rule_Grep) isRule_Spec() {}

func (*Rule_ImportGraph) isRule_Spec() {}

func (*Rule_AntiPattern) isRule_Spec() {}

func (*Rule_FunctionMetric) isRule_Spec() {}

type RuleScope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Include  []string `protobuf:"bytes,2,rep,name=include,proto3" json:"include,omitempty"` // glob patterns for files to check
	Exclude  []string `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"` // glob patterns for files to skip
}

func (x *RuleScope) Reset() {
	*x = RuleScope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleScope) ProtoMessage() {}

func (x *RuleScope) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleScope.ProtoReflect.Descriptor instead.
func (*RuleScope) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *RuleScope) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RuleScope) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *RuleScope) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type GrepSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern         string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`                                          // regex — find matching lines
	MustContain     string `protobuf:"bytes,2,opt,name=must_contain,json=mustContain,proto3" json:"must_contain,omitempty"`               // matched lines must also match this
	MustNotContain  string `protobuf:"bytes,3,opt,name=must_not_contain,json=mustNotContain,proto3" json:"must_not_contain,omitempty"`    // matched lines must NOT match this
	FileMustContain string `protobuf:"bytes,4,opt,name=file_must_contain,json=fileMustContain,proto3" json:"file_must_contain,omitempty"` // file-level prerequisite
}

func (x *GrepSpec) Reset() {
	*x = GrepSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrepSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepSpec) ProtoMessage() {}

func (x *GrepSpec) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepSpec.ProtoReflect.Descriptor instead.
func (*GrepSpec) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *GrepSpec) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *GrepSpec) GetMustContain() string {
	if x != nil {
		return x.MustContain
	}
	return ""
}

func (x *GrepSpec) GetMustNotContain() string {
	if x != nil {
		return x.MustNotContain
	}
	return ""
}

func (x *GrepSpec) GetFileMustContain() string {
	if x != nil {
		return x.FileMustContain
	}
	return ""
}

type ImportGraphSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackagePattern string   `protobuf:"bytes,1,opt,name=package_pattern,json=packagePattern,proto3" json:"package_pattern,omitempty"` // glob — which packages this rule applies to (e.g., "internal/cli/**")
	Forbidden      []string `protobuf:"bytes,2,rep,name=forbidden,proto3" json:"forbidden,omitempty"`                                 // import path patterns that are forbidden
	AllowedOnly    []string `protobuf:"bytes,3,rep,name=allowed_only,json=allowedOnly,proto3" json:"allowed_only,omitempty"`          // if non-empty, only these import patterns are allowed
}

func (x *ImportGraphSpec) Reset() {
	*x = ImportGraphSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportGraphSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportGraphSpec) ProtoMessage() {}

func (x *ImportGraphSpec) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportGraphSpec.ProtoReflect.Descriptor instead.
func (*ImportGraphSpec) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *ImportGraphSpec) GetPackagePattern() string {
	if x != nil {
		return x.PackagePattern
	}
	return ""
}

func (x *ImportGraphSpec) GetForbidden() []string {
	if x != nil {
		return x.Forbidden
	}
	return nil
}

func (x *ImportGraphSpec) GetAllowedOnly() []string {
	if x != nil {
		return x.AllowedOnly
	}
	return nil
}

type FunctionMetricSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Maximum number of lines in a function body (0 = unlimited).
	MaxLines int32 `protobuf:"varint,1,opt,name=max_lines,json=maxLines,proto3" json:"max_lines,omitempty"`
	// Maximum number of parameters (0 = unlimited).
	MaxParams int32 `protobuf:"varint,2,opt,name=max_params,json=maxParams,proto3" json:"max_params,omitempty"`
	// Maximum number of return values (0 = unlimited).
	MaxReturns int32 `protobuf:"varint,3,opt,name=max_returns,json=maxReturns,proto3" json:"max_returns,omitempty"`
}

func (x *FunctionMetricSpec) Reset() {
	*x = FunctionMetricSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionMetricSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionMetricSpec) ProtoMessage() {}

func (x *FunctionMetricSpec) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionMetricSpec.ProtoReflect.Descriptor instead.
func (*FunctionMetricSpec) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionMetricSpec) GetMaxLines() int32 {
	if x != nil {
		return x.MaxLines
	}
	return 0
}

func (x *FunctionMetricSpec) GetMaxParams() int32 {
	if x != nil {
		return x.MaxParams
	}
	return 0
}

func (x *FunctionMetricSpec) GetMaxReturns() int32 {
	if x != nil {
		return x.MaxReturns
	}
	return 0
}

type AntiPatternSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Which detectors to enable. Empty = all detectors enabled.
	// Available: global_mutable_state, init_abuse, init_side_effects, naked_goroutine,
	//
	//	swallowed_error, context_background_in_handler, sql_concatenation,
	//	uuid_v4_as_key, fat_handler, god_package
	Detectors []string `protobuf:"bytes,1,rep,name=detectors,proto3" json:"detectors,omitempty"`
}

func (x *AntiPatternSpec) Reset() {
	*x = AntiPatternSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AntiPatternSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiPatternSpec) ProtoMessage() {}

func (x *AntiPatternSpec) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiPatternSpec.ProtoReflect.Descriptor instead.
func (*AntiPatternSpec) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *AntiPatternSpec) GetDetectors() []string {
	if x != nil {
		return x.Detectors
	}
	return nil
}

type EngineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*EngineResponse_Finding
	//	*EngineResponse_CheckComplete
	//	*EngineResponse_PingResult
	//	*EngineResponse_Error
	Payload isEngineResponse_Payload `protobuf_oneof:"payload"`
}

func (x *EngineResponse) Reset() {
	*x = EngineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineResponse) ProtoMessage() {}

func (x *EngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineResponse.ProtoReflect.Descriptor instead.
func (*EngineResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{9}
}

func (m *EngineResponse) GetPayload() isEngineResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *EngineResponse) GetFinding() *Finding {
	if x, ok := x.GetPayload().(*EngineResponse_Finding); ok {
		return x.Finding
	}
	return nil
}

func (x *EngineResponse) GetCheckComplete() *CheckComplete {
	if x, ok := x.GetPayload().(*EngineResponse_CheckComplete); ok {
		return x.CheckComplete
	}
	return nil
}

func (x *EngineResponse) GetPingResult() *PingResult {
	if x, ok := x.GetPayload().(*EngineResponse_PingResult); ok {
		return x.PingResult
	}
	return nil
}

func (x *EngineResponse) GetError() *EngineError {
	if x, ok := x.GetPayload().(*EngineResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isEngineResponse_Payload interface {
	isEngineResponse_Payload()
}

type EngineResponse_Finding struct {
	Finding *Finding `protobuf:"bytes,2,opt,name=finding,proto3,oneof"`
}

type EngineResponse_CheckComplete struct {
	CheckComplete *CheckComplete `protobuf:"bytes,3,opt,name=check_complete,json=checkComplete,proto3,oneof"`
}

type EngineResponse_PingResult struct {
	PingResult *PingResult `protobuf:"bytes,6,opt,name=ping_result,json=pingResult,proto3,oneof"`
}

type EngineResponse_Error struct {
	Error *EngineError `protobuf:"bytes,10,opt,name=error,proto3,oneof"`
}

func (*EngineResponse_Finding) isEngineResponse_Payload() {}

func (*EngineResponse_CheckComplete) isEngineResponse_Payload() {}

func (*EngineResponse_PingResult) isEngineResponse_Payload() {}

func (*EngineResponse_Error) isEngineResponse_Payload() {}

type Finding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId   string   `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Severity Severity `protobuf:"varint,2,opt,name=severity,proto3,enum=engine.Severity" json:"severity,omitempty"`
	File     string   `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Line     uint32   `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column   uint32   `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	Message  string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Match    string   `protobuf:"bytes,7,opt,name=match,proto3" json:"match,omitempty"`
	Engine   string   `protobuf:"bytes,8,opt,name=engine,proto3" json:"engine,omitempty"`
}

func (x *Finding) Reset() {
	*x = Finding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{10}
}

func (x *Finding) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Finding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Finding) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Finding) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Finding) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Finding) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *Finding) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type CheckComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilesChecked    uint32        `protobuf:"varint,1,opt,name=files_checked,json=filesChecked,proto3" json:"files_checked,omitempty"`
	RulesEvaluated  uint32        `protobuf:"varint,2,opt,name=rules_evaluated,json=rulesEvaluated,proto3" json:"rules_evaluated,omitempty"`
	FindingsTotal   uint32        `protobuf:"varint,3,opt,name=findings_total,json=findingsTotal,proto3" json:"findings_total,omitempty"`
	FindingsError   uint32        `protobuf:"varint,4,opt,name=findings_error,json=findingsError,proto3" json:"findings_error,omitempty"`
	FindingsWarning uint32        `protobuf:"varint,5,opt,name=findings_warning,json=findingsWarning,proto3" json:"findings_warning,omitempty"`
	FindingsInfo    uint32        `protobuf:"varint,6,opt,name=findings_info,json=findingsInfo,proto3" json:"findings_info,omitempty"`
	DurationMs      float64       `protobuf:"fixed64,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	RuleStatuses    []*RuleStatus `protobuf:"bytes,8,rep,name=rule_statuses,json=ruleStatuses,proto3" json:"rule_statuses,omitempty"`
}

func (x *CheckComplete) Reset() {
	*x = CheckComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckComplete) ProtoMessage() {}

func (x *CheckComplete) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckComplete.ProtoReflect.Descriptor instead.
func (*CheckComplete) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{11}
}

func (x *CheckComplete) GetFilesChecked() uint32 {
	if x != nil {
		return x.FilesChecked
	}
	return 0
}

func (x *CheckComplete) GetRulesEvaluated() uint32 {
	if x != nil {
		return x.RulesEvaluated
	}
	return 0
}

func (x *CheckComplete) GetFindingsTotal() uint32 {
	if x != nil {
		return x.FindingsTotal
	}
	return 0
}

func (x *CheckComplete) GetFindingsError() uint32 {
	if x != nil {
		return x.FindingsError
	}
	return 0
}

func (x *CheckComplete) GetFindingsWarning() uint32 {
	if x != nil {
		return x.FindingsWarning
	}
	return 0
}

func (x *CheckComplete) GetFindingsInfo() uint32 {
	if x != nil {
		return x.FindingsInfo
	}
	return 0
}

func (x *CheckComplete) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CheckComplete) GetRuleStatuses() []*RuleStatus {
	if x != nil {
		return x.RuleStatuses
	}
	return nil
}

type RuleStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId string            `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Status RuleStatus_Status `protobuf:"varint,2,opt,name=status,proto3,enum=engine.RuleStatus_Status" json:"status,omitempty"`
	Error  string            `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RuleStatus) Reset() {
	*x = RuleStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleStatus) ProtoMessage() {}

func (x *RuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleStatus.ProtoReflect.Descriptor instead.
func (*RuleStatus) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{12}
}

func (x *RuleStatus) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleStatus) GetStatus() RuleStatus_Status {
	if x != nil {
		return x.Status
	}
	return RuleStatus_STATUS_UNSPECIFIED
}

func (x *RuleStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version      string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{13}
}

func (x *PingResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResult) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type EngineError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code    string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *EngineError) Reset() {
	*x = EngineError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EngineError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineError) ProtoMessage() {}

func (x *EngineError) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineError.ProtoReflect.Descriptor instead.
func (*EngineError) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{14}
}

func (x *EngineError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EngineError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_engine_proto protoreflect.FileDescriptor

var file_engine_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x22, 0x73, 0x0a, 0x0d, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x29, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x78, 0x0a, 0x0c, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x22, 0x0a,
	0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0xa6, 0x03, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a,
	0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x63,
	0x6f, 0x70, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x67, 0x72,
	0x65, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2e, 0x47, 0x72, 0x65, 0x70, 0x53, 0x70, 0x65, 0x63, 0x48, 0x00, 0x52, 0x04, 0x67, 0x72,
	0x65, 0x70, 0x12, 0x3c, 0x0a, 0x0c, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x70, 0x65,
	0x63, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x12, 0x3c, 0x0a, 0x0c, 0x61, 0x6e, 0x74, 0x69, 0x5f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e,
	0x41, 0x6e, 0x74, 0x69, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x48,
	0x00, 0x52, 0x0b, 0x61, 0x6e, 0x74, 0x69, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x45,
	0x0a, 0x0f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x53,
	0x70, 0x65, 0x63, 0x48, 0x00, 0x52, 0x0e, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x42, 0x06, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x5b, 0x0a,
	0x09, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x08, 0x47,
	0x72, 0x65, 0x70, 0x53, 0x70, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x75, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x75, 0x73, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x75, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x74,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x6d, 0x75, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x12, 0x2a,
	0x0a, 0x11, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x75, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x4d,
	0x75, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x22, 0x7b, 0x0a, 0x0f, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x70, 0x65, 0x63, 0x12, 0x27, 0x0a,
	0x0f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x50,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x62, 0x69, 0x64,
	0x64, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x62, 0x69,
	0x64, 0x64, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f,
	0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x22, 0x71, 0x0a, 0x12, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6d, 0x61, 0x78, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61,
	0x78, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6d, 0x61, 0x78, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78,
	0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6d, 0x61, 0x78, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x22, 0x2f, 0x0a, 0x0f, 0x41, 0x6e,
	0x74, 0x69, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1c, 0x0a,
	0x09, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0xec, 0x01, 0x0a, 0x0e,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b,
	0x0a, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x3e, 0x0a, 0x0e, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x70,
	0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xd8, 0x01, 0x0a, 0x07, 0x46,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x53, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x74, 0x79, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x22, 0xd5, 0x02, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f,
	0x72, 0x75, 0x6c, 0x65, 0x73, 0x5f, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x73, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x66,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0e,
	0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x5f,
	0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x66,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x23,
	0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x73, 0x12, 0x37, 0x0a, 0x0d, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0c, 0x72, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x22, 0xb3, 0x01,
	0x0a, 0x0a, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x52,
	0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x43,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x4c,
	0x45, 0x10, 0x03, 0x22, 0x4a, 0x0a, 0x0a, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22,
	0x3b, 0x0a, 0x0b, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x46, 0x0a, 0x08,
	0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x45, 0x56, 0x45,
	0x52, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x03, 0x2a, 0x76, 0x0a, 0x0a, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x4e, 0x47, 0x49, 0x4e, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x52,
	0x45, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x53, 0x54, 0x10, 0x02, 0x12, 0x10, 0x0a,
	0x0c, 0x49, 0x4d, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x47, 0x52, 0x41, 0x50, 0x48, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x4d, 0x45, 0x54, 0x52, 0x49, 0x43, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x54, 0x52, 0x55, 0x43, 0x54, 0x55, 0x52, 0x45, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x4e,
	0x54, 0x49, 0x5f, 0x50, 0x41, 0x54, 0x54, 0x45, 0x52, 0x4e, 0x10, 0x06, 0x42, 0x32, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x63, 0x73, 0x67, 0x2f,
	0x61, 0x72, 0x63, 0x68, 0x77, 0x61, 0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData = file_engine_proto_rawDesc
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_engine_proto_rawDescData)
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_engine_proto_goTypes = []interface{}{
	(Severity)(0),              // 0: engine.Severity
	(EngineType)(0),            // 1: engine.EngineType
	(RuleStatus_Status)(0),     // 2: engine.RuleStatus.Status
	(*EngineRequest)(nil),      // 3: engine.EngineRequest
	(*PingRequest)(nil),        // 4: engine.PingRequest
	(*CheckRequest)(nil),       // 5: engine.CheckRequest
	(*Rule)(nil),               // 6: engine.Rule
	(*RuleScope)(nil),          // 7: engine.RuleScope
	(*GrepSpec)(nil),           // 8: engine.GrepSpec
	(*ImportGraphSpec)(nil),    // 9: engine.ImportGraphSpec
	(*FunctionMetricSpec)(nil), // 10: engine.FunctionMetricSpec
	(*AntiPatternSpec)(nil),    // 11: engine.AntiPatternSpec
	(*EngineResponse)(nil),     // 12: engine.EngineResponse
	(*Finding)(nil),            // 13: engine.Finding
	(*CheckComplete)(nil),      // 14: engine.CheckComplete
	(*RuleStatus)(nil),         // 15: engine.RuleStatus
	(*PingResult)(nil),         // 16: engine.PingResult
	(*EngineError)(nil),        // 17: engine.EngineError
}
var file_engine_proto_depIdxs = []int32{
	5,  // 0: engine.EngineRequest.check:type_name -> engine.CheckRequest
	4,  // 1: engine.EngineRequest.ping:type_name -> engine.PingRequest
	6,  // 2: engine.CheckRequest.rules:type_name -> engine.Rule
	0,  // 3: engine.Rule.severity:type_name -> engine.Severity
	1,  // 4: engine.Rule.engine:type_name -> engine.EngineType
	7,  // 5: engine.Rule.scope:type_name -> engine.RuleScope
	8,  // 6: engine.Rule.grep:type_name -> engine.GrepSpec
	9,  // 7: engine.Rule.import_graph:type_name -> engine.ImportGraphSpec
	11, // 8: engine.Rule.anti_pattern:type_name -> engine.AntiPatternSpec
	10, // 9: engine.Rule.function_metric:type_name -> engine.FunctionMetricSpec
	13, // 10: engine.EngineResponse.finding:type_name -> engine.Finding
	14, // 11: engine.EngineResponse.check_complete:type_name -> engine.CheckComplete
	16, // 12: engine.EngineResponse.ping_result:type_name -> engine.PingResult
	17, // 13: engine.EngineResponse.error:type_name -> engine.EngineError
	0,  // 14: engine.Finding.severity:type_name -> engine.Severity
	15, // 15: engine.CheckComplete.rule_statuses:type_name -> engine.RuleStatus
	2,  // 16: engine.RuleStatus.status:type_name -> engine.RuleStatus.Status
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EngineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleScope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrepSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportGraphSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionMetricSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AntiPatternSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EngineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Finding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EngineError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_engine_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*EngineRequest_Check)(nil),
		(*EngineRequest_Ping)(nil),
	}
	file_engine_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Rule_Grep)(nil),
		(*Rule_ImportGraph)(nil),
		(*Rule_AntiPattern)(nil),
		(*Rule_FunctionMetric)(nil),
	}
	file_engine_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*EngineResponse_Finding)(nil),
		(*EngineResponse_CheckComplete)(nil),
		(*EngineResponse_PingResult)(nil),
		(*EngineResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engine_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		EnumInfos:         file_engine_proto_enumTypes,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_rawDesc = nil
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
