package guide

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// hookScriptCheck is the PostToolUse hook that runs archway check --diff HEAD.
const hookScriptCheck = `#!/bin/bash
# PostToolUse hook: run archway check --diff HEAD after file edits.
# Generated by archway guide. Do not edit manually.

# Read the edited file path from stdin (JSON).
TOOL_INPUT=$(cat)
FILE_PATH=$(echo "$TOOL_INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Skip files matching check.exclude patterns.
case "$FILE_PATH" in
  */vendor/*|*/.git/*) exit 0 ;;
esac

# Run archway check --diff HEAD scoped to changed files only.
RESULT=$(archway check --diff HEAD -o json 2>/dev/null)
EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  exit 0
fi

VIOLATIONS=$(echo "$RESULT" | jq -r '.violations | length // 0')
if [ "$VIOLATIONS" = "0" ] || [ "$VIOLATIONS" = "null" ]; then
  exit 0
fi

# Feed violations back as context for Claude to self-correct.
echo "{\"additionalContext\": \"archway check --diff HEAD found $VIOLATIONS violation(s) after editing $FILE_PATH. Run archway check --diff HEAD -o terminal for details.\"}"
exit 0
`

// hookScriptGuideRefresh is the SessionStart hook that regenerates the guide if archway.yaml changed.
const hookScriptGuideRefresh = `#!/bin/bash
# SessionStart hook: regenerate guide if archway.yaml changed.
# Generated by archway guide. Do not edit manually.

if [ ! -f "archway.yaml" ]; then
  exit 0
fi

# Hash-based staleness detection.
HASH_FILE=".archway/.guide-hash"
CURRENT_HASH=$(shasum -a 256 archway.yaml | cut -d' ' -f1)

if [ -f "$HASH_FILE" ]; then
  STORED_HASH=$(cat "$HASH_FILE")
  if [ "$CURRENT_HASH" = "$STORED_HASH" ]; then
    exit 0  # guide is fresh
  fi
fi

archway guide --target claude 2>/dev/null
if [ $? -eq 0 ]; then
  mkdir -p .archway
  echo "$CURRENT_HASH" > "$HASH_FILE"
  echo "{\"additionalContext\": \"archway guide regenerated — architecture rules updated.\"}"
fi
exit 0
`

const (
	sentinelStart = "<!-- archway:start -->"
	sentinelEnd   = "<!-- archway:end -->"
	claudeHeader  = "<!-- archway:generated -->\n"
)

// Target defines where and how to write guide output.
type Target interface {
	Name() string
	Write(projectDir, content string) error
}

// resolveTargets returns the targets matching the given selector.
func resolveTargets(selector string) ([]Target, error) {
	all := []Target{
		&claudeTarget{},
		&sentinelTarget{name: "cursor", relPath: ".cursorrules"},
		&sentinelTarget{name: "copilot", relPath: filepath.Join(".github", "copilot-instructions.md")},
		&sentinelTarget{name: "windsurf", relPath: ".windsurfrules"},
	}

	if selector == "" || selector == "all" {
		return all, nil
	}

	for _, t := range all {
		if t.Name() == selector {
			return []Target{t}, nil
		}
	}
	return nil, fmt.Errorf("unknown guide target %q (valid: all, claude, cursor, copilot, windsurf)", selector)
}

// claudeTarget writes directly to .claude/rules/archway.md.
type claudeTarget struct{}

func (t *claudeTarget) Name() string { return "claude" }

func (t *claudeTarget) Write(projectDir, content string) error {
	dir := filepath.Join(projectDir, ".claude", "rules")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create claude rules dir: %w", err)
	}
	path := filepath.Join(dir, "archway.md")
	return os.WriteFile(path, []byte(claudeHeader+content), 0o644)
}

// generateHooks creates hook scripts under .claude/hooks/ and registers them
// in .claude/settings.json via JSON-aware merge.
func generateHooks(projectDir string) error {
	hooksDir := filepath.Join(projectDir, ".claude", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("create hooks dir: %w", err)
	}

	checkScript := filepath.Join(hooksDir, "archway-check.sh")
	if err := os.WriteFile(checkScript, []byte(hookScriptCheck), 0o755); err != nil {
		return fmt.Errorf("write archway-check.sh: %w", err)
	}

	refreshScript := filepath.Join(hooksDir, "archway-guide-refresh.sh")
	if err := os.WriteFile(refreshScript, []byte(hookScriptGuideRefresh), 0o755); err != nil {
		return fmt.Errorf("write archway-guide-refresh.sh: %w", err)
	}

	hooks := map[string]any{
		"PostToolUse": []any{
			map[string]any{
				"matcher": "Write|Edit",
				"hooks": []any{
					map[string]any{
						"type":    "command",
						"command": `"$CLAUDE_PROJECT_DIR"/.claude/hooks/archway-check.sh`,
						"timeout": 10,
					},
				},
			},
		},
		"SessionStart": []any{
			map[string]any{
				"matcher": "startup",
				"hooks": []any{
					map[string]any{
						"type":    "command",
						"command": `"$CLAUDE_PROJECT_DIR"/.claude/hooks/archway-guide-refresh.sh`,
						"timeout": 10,
					},
				},
			},
		},
	}

	return mergeClaudeSettingsJSON(projectDir, hooks)
}

// mergeClaudeSettingsJSON reads .claude/settings.json, deep-merges the hooks key,
// and writes the result back. Preserves any existing user settings.
func mergeClaudeSettingsJSON(projectDir string, hooks map[string]any) error {
	settingsPath := filepath.Join(projectDir, ".claude", "settings.json")

	existing := map[string]any{}
	if data, err := os.ReadFile(settingsPath); err == nil {
		// Ignore unmarshal errors — treat corrupt file as empty.
		_ = json.Unmarshal(data, &existing)
	}

	existingHooks, _ := existing["hooks"].(map[string]any)
	if existingHooks == nil {
		existingHooks = map[string]any{}
	}

	for event, value := range hooks {
		existingHooks[event] = value
	}
	existing["hooks"] = existingHooks

	data, err := json.MarshalIndent(existing, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal settings.json: %w", err)
	}
	if err := os.WriteFile(settingsPath, append(data, '\n'), 0o644); err != nil {
		return fmt.Errorf("write settings.json: %w", err)
	}
	return nil
}

// writeGuideHash computes sha256 of archway.yaml in projectDir and writes it
// to .archway/.guide-hash for staleness detection by the SessionStart hook.
func writeGuideHash(projectDir string) error {
	yamlPath := filepath.Join(projectDir, "archway.yaml")
	data, err := os.ReadFile(yamlPath)
	if err != nil {
		// No archway.yaml — skip without error.
		return nil
	}

	sum := sha256.Sum256(data)
	hash := fmt.Sprintf("%x", sum)

	hashDir := filepath.Join(projectDir, ".archway")
	if err := os.MkdirAll(hashDir, 0o755); err != nil {
		return fmt.Errorf("create .archway dir: %w", err)
	}

	hashFile := filepath.Join(hashDir, ".guide-hash")
	if err := os.WriteFile(hashFile, []byte(hash), 0o644); err != nil {
		return fmt.Errorf("write .guide-hash: %w", err)
	}
	return nil
}

// sentinelTarget uses sentinel-based merging for shared files.
type sentinelTarget struct {
	name    string
	relPath string
}

func (t *sentinelTarget) Name() string { return t.name }

func (t *sentinelTarget) Write(projectDir, content string) error {
	path := filepath.Join(projectDir, t.relPath)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create dir for %s: %w", t.name, err)
	}

	wrapped := sentinelStart + "\n" + content + sentinelEnd + "\n"

	existing, err := os.ReadFile(path)
	if err != nil {
		// No existing file: create with sentinels.
		return os.WriteFile(path, []byte(wrapped), 0o644)
	}

	merged := mergeSentinels(string(existing), wrapped)
	return os.WriteFile(path, []byte(merged), 0o644)
}

// mergeSentinels replaces content between sentinels, or appends if none found.
func mergeSentinels(existing, wrapped string) string {
	startIdx := strings.Index(existing, sentinelStart)
	endIdx := strings.Index(existing, sentinelEnd)

	if startIdx < 0 || endIdx < 0 || endIdx < startIdx {
		// No sentinels found: append.
		if !strings.HasSuffix(existing, "\n") && existing != "" {
			existing += "\n"
		}
		return existing + "\n" + wrapped
	}

	// Replace between sentinels (inclusive).
	after := endIdx + len(sentinelEnd)
	// Consume trailing newline if present.
	if after < len(existing) && existing[after] == '\n' {
		after++
	}
	return existing[:startIdx] + wrapped + existing[after:]
}
