package guide

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// hookScriptCheck is the PostToolUse hook that runs verikt check --diff HEAD.
const hookScriptCheck = `#!/bin/bash
set -euo pipefail
# PostToolUse hook: run verikt check --diff HEAD after file edits.
# Generated by verikt guide. Do not edit manually.

# Read the edited file path from stdin (JSON).
TOOL_INPUT=$(cat)
FILE_PATH=$(echo "$TOOL_INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Skip files matching check.exclude patterns.
case "$FILE_PATH" in
  */vendor/*|*/.git/*) exit 0 ;;
esac

# Run verikt check --diff HEAD scoped to changed files only.
RESULT=$(verikt check --diff HEAD -o json 2>/dev/null) || true
EXIT_CODE=$?

if [ "$EXIT_CODE" -eq 0 ]; then
  exit 0
fi

VIOLATIONS=$(echo "$RESULT" | jq -r '.violations | length // 0')
if [ "$VIOLATIONS" = "0" ] || [ "$VIOLATIONS" = "null" ]; then
  exit 0
fi

# Feed violations back as context for Claude to self-correct.
echo "{\"additionalContext\": \"verikt check --diff HEAD found $VIOLATIONS violation(s) after editing $FILE_PATH. Run verikt check --diff HEAD -o terminal for details.\"}"
exit 0
`

// hookScriptGuideRefresh is the SessionStart hook that regenerates the guide if verikt.yaml changed.
const hookScriptGuideRefresh = `#!/bin/bash
set -euo pipefail
# SessionStart hook: regenerate guide if verikt.yaml changed.
# Generated by verikt guide. Do not edit manually.

if [ ! -f "verikt.yaml" ]; then
  exit 0
fi

# Hash-based staleness detection.
HASH_FILE=".verikt/.guide-hash"
CURRENT_HASH=$(shasum -a 256 verikt.yaml | cut -d' ' -f1)
STORED_HASH=$(cat "$HASH_FILE" 2>/dev/null || echo "")

if [ "$CURRENT_HASH" = "$STORED_HASH" ]; then
  exit 0  # guide is fresh
fi

if verikt guide --target claude 2>/dev/null; then
  mkdir -p .verikt
  TMP_HASH=$(mktemp "$HASH_FILE.XXXXXX")
  echo "$CURRENT_HASH" > "$TMP_HASH"
  mv "$TMP_HASH" "$HASH_FILE"
  echo "{\"additionalContext\": \"verikt guide regenerated — architecture rules updated.\"}"
fi
exit 0
`

const (
	sentinelStart = "<!-- verikt:start -->"
	sentinelEnd   = "<!-- verikt:end -->"
	claudeHeader  = "<!-- verikt:generated -->\n"
)

// Target defines where and how to write guide output.
type Target interface {
	Name() string
	Write(projectDir, content string) error
}

// resolveTargets returns the targets matching the given selector.
//
// "all" means every agent the project actually uses, detected from the file each
// one owns. Writing all four unconditionally left .cursorrules, .windsurfrules and
// a copilot instructions file in repositories that use none of them, recreated on
// every guide run.
//
// When no marker is present there is no signal to go on — a freshly scaffolded
// project, which is the `verikt new` case — so every target is written. An
// explicit selector always wins: the user asked for that agent.
func resolveTargets(selector, projectDir string) ([]Target, error) {
	all := []Target{
		&claudeTarget{},
		&sentinelTarget{name: "cursor", relPath: ".cursorrules"},
		&sentinelTarget{name: "copilot", relPath: filepath.Join(".github", "copilot-instructions.md")},
		&sentinelTarget{name: "windsurf", relPath: ".windsurfrules"},
	}

	if selector == "" || selector == "all" {
		inUse := make([]Target, 0, len(all))
		for _, t := range all {
			if targetInUse(t, projectDir) {
				inUse = append(inUse, t)
			}
		}
		if len(inUse) > 0 {
			return inUse, nil
		}
		return all, nil
	}

	for _, t := range all {
		if t.Name() == selector {
			return []Target{t}, nil
		}
	}
	return nil, fmt.Errorf("unknown guide target %q (valid: all, claude, cursor, copilot, windsurf)", selector)
}

// targetInUse reports whether the project already carries the file or directory
// that identifies this agent.
func targetInUse(t Target, projectDir string) bool {
	var rel string
	switch target := t.(type) {
	case *claudeTarget:
		rel = ".claude"
	case *sentinelTarget:
		rel = target.relPath
	default:
		return false
	}
	_, err := os.Stat(filepath.Join(projectDir, rel))
	return err == nil
}

// claudeTarget writes directly to .claude/rules/verikt.md.
type claudeTarget struct{}

func (t *claudeTarget) Name() string { return "claude" }

func (t *claudeTarget) Write(projectDir, content string) error {
	dir := filepath.Join(projectDir, ".claude", "rules")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create claude rules dir: %w", err)
	}
	path := filepath.Join(dir, "verikt.md")
	return os.WriteFile(path, []byte(claudeHeader+content), 0o644)
}

// generateHooks creates hook scripts under .claude/hooks/ and registers them
// in .claude/settings.json via JSON-aware merge.
func generateHooks(projectDir string) error {
	hooksDir := filepath.Join(projectDir, ".claude", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("create hooks dir: %w", err)
	}

	checkScript := filepath.Join(hooksDir, "verikt-check.sh")
	if err := os.WriteFile(checkScript, []byte(hookScriptCheck), 0o755); err != nil {
		return fmt.Errorf("write verikt-check.sh: %w", err)
	}

	refreshScript := filepath.Join(hooksDir, "verikt-guide-refresh.sh")
	if err := os.WriteFile(refreshScript, []byte(hookScriptGuideRefresh), 0o755); err != nil {
		return fmt.Errorf("write verikt-guide-refresh.sh: %w", err)
	}

	hooks := map[string]any{
		"PostToolUse": []any{
			map[string]any{
				"matcher": "Write|Edit",
				"hooks": []any{
					map[string]any{
						"type":    "command",
						"command": `"$CLAUDE_PROJECT_DIR"/.claude/hooks/verikt-check.sh`,
						"timeout": 10,
					},
				},
			},
		},
		"SessionStart": []any{
			map[string]any{
				"matcher": "startup",
				"hooks": []any{
					map[string]any{
						"type":    "command",
						"command": `"$CLAUDE_PROJECT_DIR"/.claude/hooks/verikt-guide-refresh.sh`,
						"timeout": 10,
					},
				},
			},
		},
	}

	return mergeClaudeSettingsJSON(projectDir, hooks)
}

// appendHookEntries adds verikt's entries to an event's existing list instead of
// replacing it, skipping any whose command is already registered so repeated runs
// stay idempotent.
//
// Assigning the event outright destroyed hooks the user already had: a project with
// its own PostToolUse or SessionStart hook — a formatter, a linter, another tool's
// integration — silently lost it on every `verikt guide` run.
func appendHookEntries(existing, additions any) any {
	existingList, _ := existing.([]any)
	additionList, _ := additions.([]any)

	registered := map[string]bool{}
	for _, entry := range existingList {
		for _, command := range hookCommands(entry) {
			registered[command] = true
		}
	}

	out := existingList
	for _, addition := range additionList {
		commands := hookCommands(addition)
		alreadyPresent := len(commands) > 0
		for _, command := range commands {
			if !registered[command] {
				alreadyPresent = false
			}
		}
		if alreadyPresent {
			continue
		}
		out = append(out, addition)
	}
	return out
}

// hookCommands extracts the command strings from one hook entry.
func hookCommands(entry any) []string {
	entryMap, ok := entry.(map[string]any)
	if !ok {
		return nil
	}
	inner, _ := entryMap["hooks"].([]any)
	var commands []string
	for _, h := range inner {
		hookMap, ok := h.(map[string]any)
		if !ok {
			continue
		}
		if command, ok := hookMap["command"].(string); ok {
			commands = append(commands, command)
		}
	}
	return commands
}

// mergeClaudeSettingsJSON reads .claude/settings.json, deep-merges the hooks key,
// and writes the result back. Preserves any existing user settings.
func mergeClaudeSettingsJSON(projectDir string, hooks map[string]any) error {
	settingsPath := filepath.Join(projectDir, ".claude", "settings.json")

	existing := map[string]any{}
	if data, err := os.ReadFile(settingsPath); err == nil {
		// Ignore unmarshal errors — treat corrupt file as empty.
		_ = json.Unmarshal(data, &existing)
	}

	existingHooks, _ := existing["hooks"].(map[string]any)
	if existingHooks == nil {
		existingHooks = map[string]any{}
	}

	before, _ := json.Marshal(existing)

	for event, value := range hooks {
		existingHooks[event] = appendHookEntries(existingHooks[event], value)
	}
	existing["hooks"] = existingHooks

	// Re-marshalling reorders keys and reformats every field, so writing
	// unconditionally produced a large diff on a file the run did not actually
	// change — settings.json holds the user's own hooks, and churning it on every
	// guide run makes real changes hard to spot. Compare semantically, since the
	// byte form differs from a hand-written file even when nothing was added.
	if after, err := json.Marshal(existing); err == nil && bytes.Equal(before, after) {
		return nil
	}

	data, err := json.MarshalIndent(existing, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal settings.json: %w", err)
	}
	if err := os.WriteFile(settingsPath, append(data, '\n'), 0o644); err != nil {
		return fmt.Errorf("write settings.json: %w", err)
	}
	return nil
}

// writeGuideHash computes sha256 of verikt.yaml in projectDir and writes it
// to .verikt/.guide-hash for staleness detection by the SessionStart hook.
func writeGuideHash(projectDir string) error {
	yamlPath := filepath.Join(projectDir, "verikt.yaml")
	data, err := os.ReadFile(yamlPath)
	if err != nil {
		// No verikt.yaml — skip without error.
		return nil
	}

	sum := sha256.Sum256(data)
	hash := fmt.Sprintf("%x", sum)

	hashDir := filepath.Join(projectDir, ".verikt")
	if err := os.MkdirAll(hashDir, 0o755); err != nil {
		return fmt.Errorf("create .verikt dir: %w", err)
	}

	hashFile := filepath.Join(hashDir, ".guide-hash")
	if err := os.WriteFile(hashFile, []byte(hash), 0o644); err != nil {
		return fmt.Errorf("write .guide-hash: %w", err)
	}
	return nil
}

// sentinelTarget uses sentinel-based merging for shared files.
type sentinelTarget struct {
	name    string
	relPath string
}

func (t *sentinelTarget) Name() string { return t.name }

func (t *sentinelTarget) Write(projectDir, content string) error {
	path := filepath.Join(projectDir, t.relPath)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create dir for %s: %w", t.name, err)
	}

	wrapped := sentinelStart + "\n" + content + sentinelEnd + "\n"

	existing, err := os.ReadFile(path)
	if err != nil {
		// No existing file: create with sentinels.
		return os.WriteFile(path, []byte(wrapped), 0o644)
	}

	merged := mergeSentinels(string(existing), wrapped)
	return os.WriteFile(path, []byte(merged), 0o644)
}

// mergeSentinels replaces content between sentinels, or appends if none found.
func mergeSentinels(existing, wrapped string) string {
	startIdx := strings.Index(existing, sentinelStart)
	endIdx := strings.Index(existing, sentinelEnd)

	if startIdx < 0 || endIdx < 0 || endIdx < startIdx {
		// No sentinels found: append.
		if !strings.HasSuffix(existing, "\n") && existing != "" {
			existing += "\n"
		}
		return existing + "\n" + wrapped
	}

	// Replace between sentinels (inclusive).
	after := endIdx + len(sentinelEnd)
	// Consume trailing newline if present.
	if after < len(existing) && existing[after] == '\n' {
		after++
	}
	return existing[:startIdx] + wrapped + existing[after:]
}
