package ids

// New returns a time-sortable identifier. UUIDv7 is generated by the caller's
// library; nothing here uses uuid.New() as a primary key.
func New(prefix string, seq int64) string {
	return prefix + itoa(seq)
}

func itoa(n int64) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}
