// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	site: 'https://verikt.dev',
	base: '/',
	redirects: {
		'/for/ai-coding-agents/': '/for/engineers/',
		'/for/go-developers/': '/for/engineers/',
		'/for/backend-engineers/': '/for/engineers/',
		'/for/platform-teams/': '/for/engineering-leaders/',
		'/for/microservices-teams/': '/for/engineering-leaders/',
	},
	integrations: [
		starlight({
			title: 'verikt',
			tagline: 'The architecture layer for agentic engineering',
			expressiveCode: {
				themes: ['gruvbox-dark-soft', 'gruvbox-dark-soft'],
				styleOverrides: {
					borderRadius: '0.5rem',
					codeBackground: '#1E1A14',
					codeForeground: '#E8E4DE',
					borderColor: 'rgba(232, 145, 58, 0.1)',
					focusBorder: '#E8913A',
					scrollbarThumbColor: 'rgba(232, 145, 58, 0.25)',
					scrollbarThumbHoverColor: 'rgba(232, 145, 58, 0.4)',
					frames: {
						editorBackground: '#1E1A14',
						terminalBackground: '#1E1A14',
						editorTabBarBackground: '#171614',
						terminalTitlebarBackground: '#171614',
					},
				},
			},
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/diktahq/verikt' }],
			components: {
				Head: './src/components/Head.astro',
				Header: './src/components/Header.astro',
				SiteTitle: './src/components/SiteTitle.astro',
				Footer: './src/components/Footer.astro',
			},
			editLink: {
				baseUrl: 'https://github.com/diktahq/verikt/edit/main/website/',
			},
			customCss: ['./src/styles/custom.css'],
			head: [
				{ tag: 'script', attrs: { async: true, src: 'https://www.googletagmanager.com/gtag/js?id=G-PSXJ5N0EDV' } },
				{ tag: 'script', content: "window.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('js', new Date());\ngtag('config', 'G-PSXJ5N0EDV');" },
				{ tag: 'meta', attrs: { property: 'og:type', content: 'website' } },
				{ tag: 'meta', attrs: { property: 'og:image', content: 'https://verikt.dev/og.png' } },
				{ tag: 'meta', attrs: { name: 'twitter:card', content: 'summary_large_image' } },
				{ tag: 'meta', attrs: { name: 'twitter:image', content: 'https://verikt.dev/og.png' } },
				{ tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' } },
				{ tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true } },
				{ tag: 'link', attrs: { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@1&family=JetBrains+Mono:wght@400;500&display=swap' } },
			],
			sidebar: [
				{
					label: 'Getting Started',
					items: [
						{ label: 'Introduction', slug: 'getting-started/introduction' },
						{ label: 'Installation', slug: 'getting-started/installation' },
						{ label: 'Quick Start with AI Agents', slug: 'getting-started/ai-agents' },
						{ label: 'Quick Start with CLI', slug: 'getting-started/cli' },
					],
				},
				{
					label: 'For',
					items: [
						{ label: 'For Engineers', slug: 'for/engineers' },
						{ label: 'For Engineering Leaders', slug: 'for/engineering-leaders' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Prompt Engineering', slug: 'guides/prompt-engineering' },
						{ label: 'Adding Capabilities', slug: 'guides/adding-capabilities' },
						{ label: 'CI Integration', slug: 'guides/ci-integration' },
						{ label: 'Detecting Architecture Drift', slug: 'guides/architecture-drift' },
						{ label: 'Architecture Rules for Claude Code', slug: 'guides/claude-code-architecture-rules' },
						{ label: 'Architecture Rules for Cursor', slug: 'guides/cursor-rules-architecture' },
						{ label: 'Architecture Rules for Copilot', slug: 'guides/copilot-instructions-architecture' },
					],
				},
				{
					label: 'Experiments',
					items: [
						{ label: 'Overview', slug: 'experiments' },
						{ label: 'EXP-01 — Same Task, Different Architecture', slug: 'experiments/exp-01' },
						{ label: 'EXP-02 — Three Engineers, One Standard', slug: 'experiments/exp-02' },
						{ label: 'EXP-03 — Build Me a Job Runner', slug: 'experiments/exp-03' },
						{ label: 'EXP-04 — New Feature, Existing Service', slug: 'experiments/exp-04' },
						{ label: 'EXP-05 — Does the Prompt Even Matter?', slug: 'experiments/exp-05' },
						{ label: 'EXP-06 — Someone Else\'s Codebase', slug: 'experiments/exp-06' },
						{ label: 'EXP-07 — Consistency on Fixtures', slug: 'experiments/exp-07' },
						{ label: 'EXP-08 — Anti-Pattern Prevention', slug: 'experiments/exp-08' },
						{ label: 'EXP-09 — Does the Guide Expand Recommendations?', slug: 'experiments/exp-09' },
						{ label: 'Methodology', slug: 'experiments/methodology' },
					],
				},
				{
					label: 'Concepts',
					items: [
						{ label: 'Why verikt exists', slug: 'concepts/why-verikt-exists' },
						{ label: 'Agentic Engineering', slug: 'concepts/agentic-engineering' },
						{ label: 'Context Engineering', slug: 'concepts/context-engineering' },
						{ label: 'How It Works', slug: 'concepts/how-it-works' },
						{ label: 'Architectures', slug: 'concepts/architectures' },
						{ label: 'Capabilities', slug: 'concepts/capabilities' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'Capabilities Matrix', slug: 'reference/capabilities-matrix' },
						{ label: 'Feature Matrix', slug: 'reference/features' },
						{ label: 'CLI Commands', slug: 'reference/cli' },
						{ label: 'verikt.yaml', slug: 'reference/verikt-yaml' },
						{ label: 'verikt guide', slug: 'reference/guide' },
					],
				},
				{
					label: 'Capabilities',
					collapsed: true,
					items: [
						{
							label: 'Transport & API',
							collapsed: true,
							items: [
								{ label: 'http-api', slug: 'capabilities/http-api' },
								{ label: 'grpc', slug: 'capabilities/grpc' },
								{ label: 'graphql', slug: 'capabilities/graphql' },
								{ label: 'websocket', slug: 'capabilities/websocket' },
								{ label: 'sse', slug: 'capabilities/sse' },
								{ label: 'bff', slug: 'capabilities/bff' },
								{ label: 'cors', slug: 'capabilities/cors' },
								{ label: 'rate-limiting', slug: 'capabilities/rate-limiting' },
								{ label: 'timeout', slug: 'capabilities/timeout' },
								{ label: 'api-versioning', slug: 'capabilities/api-versioning' },
							],
						},
						{
							label: 'Data & Storage',
							collapsed: true,
							items: [
								{ label: 'postgres', slug: 'capabilities/postgres' },
								{ label: 'mysql', slug: 'capabilities/mysql' },
								{ label: 'mongodb', slug: 'capabilities/mongodb' },
								{ label: 'sqlite', slug: 'capabilities/sqlite' },
								{ label: 'dynamodb', slug: 'capabilities/dynamodb' },
								{ label: 'redis', slug: 'capabilities/redis' },
								{ label: 'elasticsearch', slug: 'capabilities/elasticsearch' },
								{ label: 's3', slug: 'capabilities/s3' },
								{ label: 'migrations', slug: 'capabilities/migrations' },
								{ label: 'repository', slug: 'capabilities/repository' },
							],
						},
						{
							label: 'Messaging & Events',
							collapsed: true,
							items: [
								{ label: 'kafka-consumer', slug: 'capabilities/kafka-consumer' },
								{ label: 'nats', slug: 'capabilities/nats' },
								{ label: 'event-bus', slug: 'capabilities/event-bus' },
								{ label: 'outbox', slug: 'capabilities/outbox' },
								{ label: 'saga', slug: 'capabilities/saga' },
								{ label: 'worker', slug: 'capabilities/worker' },
							],
						},
						{
							label: 'Resilience',
							collapsed: true,
							items: [
								{ label: 'circuit-breaker', slug: 'capabilities/circuit-breaker' },
								{ label: 'retry', slug: 'capabilities/retry' },
								{ label: 'bulkhead', slug: 'capabilities/bulkhead' },
								{ label: 'idempotency', slug: 'capabilities/idempotency' },
								{ label: 'graceful', slug: 'capabilities/graceful' },
							],
						},
						{
							label: 'Security',
							collapsed: true,
							items: [
								{ label: 'auth-jwt', slug: 'capabilities/auth-jwt' },
								{ label: 'oauth2', slug: 'capabilities/oauth2' },
								{ label: 'encryption', slug: 'capabilities/encryption' },
								{ label: 'multi-tenancy', slug: 'capabilities/multi-tenancy' },
								{ label: 'request-id', slug: 'capabilities/request-id' },
							],
						},
						{
							label: 'Observability',
							collapsed: true,
							items: [
								{ label: 'health', slug: 'capabilities/health' },
								{ label: 'observability', slug: 'capabilities/observability' },
								{ label: 'audit-log', slug: 'capabilities/audit-log' },
								{ label: 'http-client', slug: 'capabilities/http-client' },
							],
						},
						{
							label: 'Architecture Patterns',
							collapsed: true,
							items: [
								{ label: 'cqrs', slug: 'capabilities/cqrs' },
								{ label: 'ddd', slug: 'capabilities/ddd' },
							],
						},
						{
							label: 'Application Core',
							collapsed: true,
							items: [
								{ label: 'platform', slug: 'capabilities/platform' },
								{ label: 'bootstrap', slug: 'capabilities/bootstrap' },
								{ label: 'validation', slug: 'capabilities/validation' },
								{ label: 'uuid', slug: 'capabilities/uuid' },
								{ label: 'feature-flags', slug: 'capabilities/feature-flags' },
								{ label: 'scheduler', slug: 'capabilities/scheduler' },
							],
						},
						{
							label: 'Frontend',
							collapsed: true,
							items: [
								{ label: 'templ', slug: 'capabilities/templ' },
								{ label: 'htmx', slug: 'capabilities/htmx' },
								{ label: 'static-assets', slug: 'capabilities/static-assets' },
								{ label: 'i18n', slug: 'capabilities/i18n' },
							],
						},
						{
							label: 'Email & Notifications',
							collapsed: true,
							items: [
								{ label: 'email-gateway', slug: 'capabilities/email-gateway' },
								{ label: 'mailpit', slug: 'capabilities/mailpit' },
							],
						},
						{
							label: 'Development & DevOps',
							collapsed: true,
							items: [
								{ label: 'docker', slug: 'capabilities/docker' },
								{ label: 'devcontainer', slug: 'capabilities/devcontainer' },
								{ label: 'ci-github', slug: 'capabilities/ci-github' },
								{ label: 'ci-gitlab', slug: 'capabilities/ci-gitlab' },
								{ label: 'ci-bitbucket', slug: 'capabilities/ci-bitbucket' },
								{ label: 'makefile', slug: 'capabilities/makefile' },
								{ label: 'linting', slug: 'capabilities/linting' },
								{ label: 'testing', slug: 'capabilities/testing' },
								{ label: 'pre-commit', slug: 'capabilities/pre-commit' },
							],
						},
					],
				},
				{
					label: 'Compare',
					collapsed: true,
					items: [
						{ label: 'All Comparisons', slug: 'compare' },
						{ label: 'Hexagonal vs Clean', slug: 'compare/hexagonal-vs-clean' },
						{ label: 'Hexagonal vs Layered', slug: 'compare/hexagonal-vs-layered' },
						{ label: 'Hexagonal vs Flat', slug: 'compare/hexagonal-vs-flat' },
						{ label: 'Clean vs Layered', slug: 'compare/clean-vs-layered' },
						{ label: 'Clean vs Flat', slug: 'compare/clean-vs-flat' },
						{ label: 'Layered vs Flat', slug: 'compare/layered-vs-flat' },
					],
				},
				{
					label: 'Glossary',
					collapsed: true,
					items: [
						{ label: 'All Terms', slug: 'glossary' },
						{ label: 'Bulkhead Pattern', slug: 'glossary/bulkhead-pattern' },
						{ label: 'Circuit Breaker', slug: 'glossary/circuit-breaker' },
						{ label: 'Clean Architecture', slug: 'glossary/clean-architecture' },
						{ label: 'CQRS', slug: 'glossary/cqrs' },
						{ label: 'Dependency Injection', slug: 'glossary/dependency-injection' },
						{ label: 'Domain-Driven Design', slug: 'glossary/domain-driven-design' },
						{ label: 'Event-Driven Architecture', slug: 'glossary/event-driven-architecture' },
						{ label: 'Hexagonal Architecture', slug: 'glossary/hexagonal-architecture' },
						{ label: 'Idempotency', slug: 'glossary/idempotency' },
						{ label: 'JWT Authentication', slug: 'glossary/jwt-authentication' },
						{ label: 'Layered Architecture', slug: 'glossary/layered-architecture' },
						{ label: 'OpenTelemetry', slug: 'glossary/opentelemetry' },
						{ label: 'Outbox Pattern', slug: 'glossary/outbox-pattern' },
						{ label: 'Ports and Adapters', slug: 'glossary/ports-and-adapters' },
						{ label: 'Rate Limiting', slug: 'glossary/rate-limiting' },
						{ label: 'Repository Pattern', slug: 'glossary/repository-pattern' },
						{ label: 'Saga Pattern', slug: 'glossary/saga-pattern' },
						{ label: 'Service Mesh', slug: 'glossary/service-mesh' },
					],
				},
				{ label: 'Changelog', slug: 'changelog' },
				{ label: 'About', slug: 'about' },
			],
		}),
	],
});
