// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	site: 'https://archway.dcsg.me',
	base: '/',
	integrations: [
		starlight({
			title: 'Archway',
			tagline: 'Architecture-aware service composer and enforcer',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/dcsg/archway' }],
			components: {
				Header: './src/components/Header.astro',
				SiteTitle: './src/components/SiteTitle.astro',
				Footer: './src/components/Footer.astro',
			},
			editLink: {
				baseUrl: 'https://github.com/dcsg/archway/edit/main/website/',
			},
			customCss: ['./src/styles/custom.css'],
			head: [
				{ tag: 'script', attrs: { async: true, src: 'https://www.googletagmanager.com/gtag/js?id=G-PSXJ5N0EDV' } },
				{ tag: 'script', content: "window.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('js', new Date());\ngtag('config', 'G-PSXJ5N0EDV');" },
				{ tag: 'meta', attrs: { property: 'og:type', content: 'website' } },
				{ tag: 'meta', attrs: { property: 'og:title', content: 'archway — Architecture-aware service composer and enforcer' } },
				{ tag: 'meta', attrs: { property: 'og:description', content: 'Compose production-ready services from 4 architecture patterns and 63 modular capabilities. Guide, compose, analyze, and enforce architecture rules in CI.' } },
				{ tag: 'meta', attrs: { property: 'og:image', content: 'https://archway.dcsg.me/og.png' } },
				{ tag: 'meta', attrs: { name: 'twitter:card', content: 'summary_large_image' } },
				{ tag: 'meta', attrs: { name: 'twitter:title', content: 'archway — Architecture-aware service composer and enforcer' } },
				{ tag: 'meta', attrs: { name: 'twitter:description', content: 'Compose production-ready services from 4 architecture patterns and 63 modular capabilities. Guide, compose, analyze, and enforce architecture rules in CI.' } },
				{ tag: 'meta', attrs: { name: 'twitter:image', content: 'https://archway.dcsg.me/og.png' } },
				{ tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' } },
				{ tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: true } },
				{ tag: 'link', attrs: { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@1&display=swap' } },
			],
			sidebar: [
				{
					label: 'Getting Started',
					items: [
						{ label: 'Introduction', slug: 'getting-started/introduction' },
						{ label: 'Installation', slug: 'getting-started/installation' },
						{ label: 'Quick Start with AI Agents', slug: 'getting-started/ai-agents' },
						{ label: 'Quick Start with CLI', slug: 'getting-started/cli' },
					],
				},
				{
					label: 'Concepts',
					items: [
						{ label: 'How It Works', slug: 'concepts/how-it-works' },
						{ label: 'Architectures', slug: 'concepts/architectures' },
						{ label: 'Capabilities', slug: 'concepts/capabilities' },
					],
				},
				{
				label: 'Capabilities',
				collapsed: true,
				items: [
					{ label: 'api-versioning', slug: 'capabilities/api-versioning' },
					{ label: 'audit-log', slug: 'capabilities/audit-log' },
					{ label: 'auth-jwt', slug: 'capabilities/auth-jwt' },
					{ label: 'bff', slug: 'capabilities/bff' },
					{ label: 'bootstrap', slug: 'capabilities/bootstrap' },
					{ label: 'bulkhead', slug: 'capabilities/bulkhead' },
					{ label: 'ci-bitbucket', slug: 'capabilities/ci-bitbucket' },
					{ label: 'ci-github', slug: 'capabilities/ci-github' },
					{ label: 'ci-gitlab', slug: 'capabilities/ci-gitlab' },
					{ label: 'circuit-breaker', slug: 'capabilities/circuit-breaker' },
					{ label: 'cors', slug: 'capabilities/cors' },
					{ label: 'cqrs', slug: 'capabilities/cqrs' },
					{ label: 'ddd', slug: 'capabilities/ddd' },
					{ label: 'devcontainer', slug: 'capabilities/devcontainer' },
					{ label: 'docker', slug: 'capabilities/docker' },
					{ label: 'dynamodb', slug: 'capabilities/dynamodb' },
					{ label: 'elasticsearch', slug: 'capabilities/elasticsearch' },
					{ label: 'email-gateway', slug: 'capabilities/email-gateway' },
					{ label: 'encryption', slug: 'capabilities/encryption' },
					{ label: 'event-bus', slug: 'capabilities/event-bus' },
					{ label: 'feature-flags', slug: 'capabilities/feature-flags' },
					{ label: 'graceful', slug: 'capabilities/graceful' },
					{ label: 'graphql', slug: 'capabilities/graphql' },
					{ label: 'grpc', slug: 'capabilities/grpc' },
					{ label: 'health', slug: 'capabilities/health' },
					{ label: 'htmx', slug: 'capabilities/htmx' },
					{ label: 'http-api', slug: 'capabilities/http-api' },
					{ label: 'http-client', slug: 'capabilities/http-client' },
					{ label: 'i18n', slug: 'capabilities/i18n' },
					{ label: 'idempotency', slug: 'capabilities/idempotency' },
					{ label: 'kafka-consumer', slug: 'capabilities/kafka-consumer' },
					{ label: 'linting', slug: 'capabilities/linting' },
					{ label: 'mailpit', slug: 'capabilities/mailpit' },
					{ label: 'makefile', slug: 'capabilities/makefile' },
					{ label: 'migrations', slug: 'capabilities/migrations' },
					{ label: 'mongodb', slug: 'capabilities/mongodb' },
					{ label: 'multi-tenancy', slug: 'capabilities/multi-tenancy' },
					{ label: 'mysql', slug: 'capabilities/mysql' },
					{ label: 'nats', slug: 'capabilities/nats' },
					{ label: 'observability', slug: 'capabilities/observability' },
					{ label: 'oauth2', slug: 'capabilities/oauth2' },
					{ label: 'outbox', slug: 'capabilities/outbox' },
					{ label: 'platform', slug: 'capabilities/platform' },
					{ label: 'postgres', slug: 'capabilities/postgres' },
					{ label: 'pre-commit', slug: 'capabilities/pre-commit' },
					{ label: 'rate-limiting', slug: 'capabilities/rate-limiting' },
					{ label: 'redis', slug: 'capabilities/redis' },
					{ label: 'repository', slug: 'capabilities/repository' },
					{ label: 'request-id', slug: 'capabilities/request-id' },
					{ label: 'retry', slug: 'capabilities/retry' },
					{ label: 's3', slug: 'capabilities/s3' },
					{ label: 'saga', slug: 'capabilities/saga' },
					{ label: 'scheduler', slug: 'capabilities/scheduler' },
					{ label: 'sqlite', slug: 'capabilities/sqlite' },
					{ label: 'sse', slug: 'capabilities/sse' },
					{ label: 'static-assets', slug: 'capabilities/static-assets' },
					{ label: 'templ', slug: 'capabilities/templ' },
					{ label: 'testing', slug: 'capabilities/testing' },
					{ label: 'timeout', slug: 'capabilities/timeout' },
					{ label: 'uuid', slug: 'capabilities/uuid' },
					{ label: 'validation', slug: 'capabilities/validation' },
					{ label: 'websocket', slug: 'capabilities/websocket' },
					{ label: 'worker', slug: 'capabilities/worker' },
				],
			},
			{
					label: 'Reference',
					items: [
						{ label: 'Capabilities Matrix', slug: 'reference/capabilities-matrix' },
						{ label: 'Feature Matrix', slug: 'reference/features' },
						{ label: 'CLI Commands', slug: 'reference/cli' },
						{ label: 'archway.yaml', slug: 'reference/archway-yaml' },
						{ label: 'archway guide', slug: 'reference/guide' },
					],
				},
				{
					label: 'Compare',
					collapsed: true,
					items: [
						{ label: 'All Comparisons', slug: 'compare' },
						{ label: 'Hexagonal vs Clean', slug: 'compare/hexagonal-vs-clean' },
						{ label: 'Hexagonal vs Layered', slug: 'compare/hexagonal-vs-layered' },
						{ label: 'Hexagonal vs Flat', slug: 'compare/hexagonal-vs-flat' },
						{ label: 'Clean vs Layered', slug: 'compare/clean-vs-layered' },
						{ label: 'Clean vs Flat', slug: 'compare/clean-vs-flat' },
						{ label: 'Layered vs Flat', slug: 'compare/layered-vs-flat' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Building a REST API', slug: 'guides/rest-api' },
						{ label: 'Adding Capabilities', slug: 'guides/adding-capabilities' },
						{ label: 'Detecting Architecture Drift', slug: 'guides/architecture-drift' },
						{ label: 'CI Integration', slug: 'guides/ci-integration' },
					],
				},
				{
					label: 'For',
					collapsed: true,
					items: [
						{ label: 'All Personas', slug: 'for' },
						{ label: 'Go Developers', slug: 'for/go-developers' },
						{ label: 'Microservices Teams', slug: 'for/microservices-teams' },
						{ label: 'Backend Engineers', slug: 'for/backend-engineers' },
						{ label: 'Platform & SRE Teams', slug: 'for/platform-teams' },
						{ label: 'AI Coding Agents', slug: 'for/ai-coding-agents' },
					],
				},
				{
					label: 'Glossary',
					collapsed: true,
					items: [
						{ label: 'All Terms', slug: 'glossary' },
						{ label: 'Bulkhead Pattern', slug: 'glossary/bulkhead-pattern' },
						{ label: 'Circuit Breaker', slug: 'glossary/circuit-breaker' },
						{ label: 'Clean Architecture', slug: 'glossary/clean-architecture' },
						{ label: 'CQRS', slug: 'glossary/cqrs' },
						{ label: 'Dependency Injection', slug: 'glossary/dependency-injection' },
						{ label: 'Domain-Driven Design', slug: 'glossary/domain-driven-design' },
						{ label: 'Event-Driven Architecture', slug: 'glossary/event-driven-architecture' },
						{ label: 'Hexagonal Architecture', slug: 'glossary/hexagonal-architecture' },
						{ label: 'Idempotency', slug: 'glossary/idempotency' },
						{ label: 'JWT Authentication', slug: 'glossary/jwt-authentication' },
						{ label: 'Layered Architecture', slug: 'glossary/layered-architecture' },
						{ label: 'OpenTelemetry', slug: 'glossary/opentelemetry' },
						{ label: 'Outbox Pattern', slug: 'glossary/outbox-pattern' },
						{ label: 'Ports and Adapters', slug: 'glossary/ports-and-adapters' },
						{ label: 'Rate Limiting', slug: 'glossary/rate-limiting' },
						{ label: 'Repository Pattern', slug: 'glossary/repository-pattern' },
						{ label: 'Saga Pattern', slug: 'glossary/saga-pattern' },
						{ label: 'Service Mesh', slug: 'glossary/service-mesh' },
					],
				},
			],
		}),
	],
});
